### ISSUE TITLE
Failures due to glueviz logo file

### ISSUE THREAD

**Issue by bsipocz** [astropy/conda-channel-astropy#113]
For some reason the glue logo file issue has come up again, e.g. [here](https://travis-ci.org/astropy/conda-channel-astropy/jobs/187375583#L1110), even thought there was no version updates. 

As a workaround the glue build is disabled for now, but it would be nice to find a solution at some point.

**Comment by mwcraig** [comment]
The way conda-forge packages are handled right now is a little silly because we're using conda-build-all to both build packages and copy them. For conda-build-all to work it needs a recipe for each package, even ones like glue that it won't actually build. 

To get the recipe it just copies the meta.yml from the conda-forge feedstock repo. Because glue's meta.yml refers to its icon (the png file), and I'm not copying the png file, the build fails.

The easy fix would be to clone the whole recipe folder or to special-case glue.

The correct fix, I think, is to handle copying separately, especially now that travis has CRON jobs.

**Comment by bsipocz** [comment]
Closing this as glue now copied over from conda-forge in all cases, independently of the version info.
