### ISSUE TITLE
Build and provide conda packages for astropy LTS 

### ISSUE THREAD

**Issue by bsipocz** [astropy/conda-channel-astropy#127]
I think it would be valuable to provide conda packages for the LTS releases somewhere. continuum stopped building them as we have never releases, and we only build them for linux and for CI purposes in the ``astropy-ci-extras`` channel (at least we advertise that channel as such).

I would propose to define a subset of numpy and python versions (the numpy probably should be quite generous, as someone sticking to astropy LTS would probably have an old version of numpy, too), and host the packages in the astropy channel, too.

cc @mwcraig @eteq @astrofrog

**Comment by mwcraig** [comment]
yeah, that probably makes sense. What would be easy to support, I think, is building LTS for whatever old combinations of numpy/python are available on either defaults or conda-forge. So in other words, instead of all numpy >=1.7 on all pythons >=3.4 and 2.7, just the subset of cases for which we would not have to build custom numpy. (would really like to avoid that if possible).

**Comment by bsipocz** [comment]
@mwcraig - Available combinations sound great, much better than have nothing.

**Comment by astrofrog** [comment]
@mwcraig - the LTS releases are available on conda-forge but aren't being copied over here. Would it be possible to fix the copying so that 2.0.5 to 2.0.9 are copied over?

**Comment by mwcraig** [comment]
I believe this is working now, so closing
