### ISSUE TITLE
reproject>=0.7 not compatible with python>=3.7 on astropy conda channel while it works correctly via pypi using pip.

### ISSUE THREAD

**Issue by emirkmo** [astropy/conda-channel-astropy#182]
See issue from [astropy/reproject/#238](https://github.com/astropy/reproject/issues/238)

Attempting to install the latest reproject package from the astropy conda channel claims reproject is not compatible with python >=3.7.

**Comment by mwcraig** [comment]
@emirkmo -- Thanks for reporting this! Can you let me know what output you get from `conda config --show channels`? I took a quick look hoping the issue was a missing version requirement or something and don't see that. I want to try to reproduce the issue on my machine  but knowing the channels you use would be helpful.

Also, what platform are you on?

Thanks!

**Comment by mwcraig** [comment]
I'm closing this but if you are still experiencing the issue please feel free to reopen it.
