### ISSUE TITLE
Adding galpy conda build

### ISSUE THREAD

**Issue by bsipocz** [astropy/conda-channel-astropy#83]
Since galpy is affiliated, I wonder whether it may be good for consistency to add a conda build for it, too.

cc @mwcraig @jobovy

**Comment by jobovy** [comment]
Yes, this would be great! I know that @mwcraig started working on a galpy conda build, but I think it was difficult because of the GSL dependency. I've also released a newer version of galpy since that first effort. I haven't ever built a conda package, but am happy to help out with this in any way that I can.

**Comment by mwcraig** [comment]
The earlier work was here: https://github.com/astropy/conda-builder-affiliated/pull/82

I _think_ (but have not checked yet) that GSL is now available on conda-forge, which would solve that dependency problem nicely.

**Comment by mwcraig** [comment]
Yep, gsl is now in conda-forge, so galpy should now be pretty straightforward (it is only available on mac/linux, but that is a good start).

**Comment by jobovy** [comment]
I'd like there to be a conda build for galpy, but I have no experience with creating conda recipes. Given that the GSL is now on conda-forge, is the solution basically to take @mwcraig's earlier work, add ``gsl`` to the ``meta.yaml`` file's ``build`` and ``run`` sections? If so, I'm happy to create a pull request, but if there is more involved then I would appreciate some pointers. Thanks!

**Comment by mwcraig** [comment]
@jobovy -- since this will use `gsl` from conda-forge, I think it would make sense to create the recipe over their (and then the package will be copied from there to the astropy channel).

If you want to open the PR for that, instructions are at the readme for https://github.com/conda-forge/staged-recipes, or, if it can wait a couple days, I can open the PR and ping you on it.

**Comment by jobovy** [comment]
@mwcraig -- Thanks for getting back to me! Again, I have no experience with conda or conda-forge, so I'm happy to wait for a few days if you think you'll have time then. But let me know if I can help (galpy is on v1.2 now and I think the PyPI package should be good for packaging).

**Comment by mwcraig** [comment]
Closing, because: https://anaconda.org/astropy/galpy 😀
